// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_Application.Database;

namespace My_Application.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201013063153_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("My_Application.Models.OneHundredDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Day001")
                        .HasColumnType("bit");

                    b.Property<bool>("Day002")
                        .HasColumnType("bit");

                    b.Property<bool>("Day003")
                        .HasColumnType("bit");

                    b.Property<bool>("Day004")
                        .HasColumnType("bit");

                    b.Property<bool>("Day005")
                        .HasColumnType("bit");

                    b.Property<bool>("Day006")
                        .HasColumnType("bit");

                    b.Property<bool>("Day007")
                        .HasColumnType("bit");

                    b.Property<bool>("Day008")
                        .HasColumnType("bit");

                    b.Property<bool>("Day009")
                        .HasColumnType("bit");

                    b.Property<bool>("Day010")
                        .HasColumnType("bit");

                    b.Property<bool>("Day011")
                        .HasColumnType("bit");

                    b.Property<bool>("Day012")
                        .HasColumnType("bit");

                    b.Property<bool>("Day013")
                        .HasColumnType("bit");

                    b.Property<bool>("Day014")
                        .HasColumnType("bit");

                    b.Property<bool>("Day015")
                        .HasColumnType("bit");

                    b.Property<bool>("Day016")
                        .HasColumnType("bit");

                    b.Property<bool>("Day017")
                        .HasColumnType("bit");

                    b.Property<bool>("Day018")
                        .HasColumnType("bit");

                    b.Property<bool>("Day019")
                        .HasColumnType("bit");

                    b.Property<bool>("Day020")
                        .HasColumnType("bit");

                    b.Property<bool>("Day021")
                        .HasColumnType("bit");

                    b.Property<bool>("Day022")
                        .HasColumnType("bit");

                    b.Property<bool>("Day023")
                        .HasColumnType("bit");

                    b.Property<bool>("Day024")
                        .HasColumnType("bit");

                    b.Property<bool>("Day025")
                        .HasColumnType("bit");

                    b.Property<bool>("Day026")
                        .HasColumnType("bit");

                    b.Property<bool>("Day027")
                        .HasColumnType("bit");

                    b.Property<bool>("Day028")
                        .HasColumnType("bit");

                    b.Property<bool>("Day029")
                        .HasColumnType("bit");

                    b.Property<bool>("Day030")
                        .HasColumnType("bit");

                    b.Property<bool>("Day031")
                        .HasColumnType("bit");

                    b.Property<bool>("Day032")
                        .HasColumnType("bit");

                    b.Property<bool>("Day033")
                        .HasColumnType("bit");

                    b.Property<bool>("Day034")
                        .HasColumnType("bit");

                    b.Property<bool>("Day035")
                        .HasColumnType("bit");

                    b.Property<bool>("Day036")
                        .HasColumnType("bit");

                    b.Property<bool>("Day037")
                        .HasColumnType("bit");

                    b.Property<bool>("Day038")
                        .HasColumnType("bit");

                    b.Property<bool>("Day039")
                        .HasColumnType("bit");

                    b.Property<bool>("Day040")
                        .HasColumnType("bit");

                    b.Property<bool>("Day041")
                        .HasColumnType("bit");

                    b.Property<bool>("Day042")
                        .HasColumnType("bit");

                    b.Property<bool>("Day043")
                        .HasColumnType("bit");

                    b.Property<bool>("Day044")
                        .HasColumnType("bit");

                    b.Property<bool>("Day045")
                        .HasColumnType("bit");

                    b.Property<bool>("Day046")
                        .HasColumnType("bit");

                    b.Property<bool>("Day047")
                        .HasColumnType("bit");

                    b.Property<bool>("Day048")
                        .HasColumnType("bit");

                    b.Property<bool>("Day049")
                        .HasColumnType("bit");

                    b.Property<bool>("Day050")
                        .HasColumnType("bit");

                    b.Property<bool>("Day051")
                        .HasColumnType("bit");

                    b.Property<bool>("Day052")
                        .HasColumnType("bit");

                    b.Property<bool>("Day053")
                        .HasColumnType("bit");

                    b.Property<bool>("Day054")
                        .HasColumnType("bit");

                    b.Property<bool>("Day055")
                        .HasColumnType("bit");

                    b.Property<bool>("Day056")
                        .HasColumnType("bit");

                    b.Property<bool>("Day057")
                        .HasColumnType("bit");

                    b.Property<bool>("Day058")
                        .HasColumnType("bit");

                    b.Property<bool>("Day059")
                        .HasColumnType("bit");

                    b.Property<bool>("Day060")
                        .HasColumnType("bit");

                    b.Property<bool>("Day061")
                        .HasColumnType("bit");

                    b.Property<bool>("Day062")
                        .HasColumnType("bit");

                    b.Property<bool>("Day063")
                        .HasColumnType("bit");

                    b.Property<bool>("Day064")
                        .HasColumnType("bit");

                    b.Property<bool>("Day065")
                        .HasColumnType("bit");

                    b.Property<bool>("Day066")
                        .HasColumnType("bit");

                    b.Property<bool>("Day067")
                        .HasColumnType("bit");

                    b.Property<bool>("Day068")
                        .HasColumnType("bit");

                    b.Property<bool>("Day069")
                        .HasColumnType("bit");

                    b.Property<bool>("Day070")
                        .HasColumnType("bit");

                    b.Property<bool>("Day071")
                        .HasColumnType("bit");

                    b.Property<bool>("Day072")
                        .HasColumnType("bit");

                    b.Property<bool>("Day073")
                        .HasColumnType("bit");

                    b.Property<bool>("Day074")
                        .HasColumnType("bit");

                    b.Property<bool>("Day075")
                        .HasColumnType("bit");

                    b.Property<bool>("Day076")
                        .HasColumnType("bit");

                    b.Property<bool>("Day077")
                        .HasColumnType("bit");

                    b.Property<bool>("Day078")
                        .HasColumnType("bit");

                    b.Property<bool>("Day079")
                        .HasColumnType("bit");

                    b.Property<bool>("Day080")
                        .HasColumnType("bit");

                    b.Property<bool>("Day081")
                        .HasColumnType("bit");

                    b.Property<bool>("Day082")
                        .HasColumnType("bit");

                    b.Property<bool>("Day083")
                        .HasColumnType("bit");

                    b.Property<bool>("Day084")
                        .HasColumnType("bit");

                    b.Property<bool>("Day085")
                        .HasColumnType("bit");

                    b.Property<bool>("Day086")
                        .HasColumnType("bit");

                    b.Property<bool>("Day087")
                        .HasColumnType("bit");

                    b.Property<bool>("Day088")
                        .HasColumnType("bit");

                    b.Property<bool>("Day089")
                        .HasColumnType("bit");

                    b.Property<bool>("Day090")
                        .HasColumnType("bit");

                    b.Property<bool>("Day091")
                        .HasColumnType("bit");

                    b.Property<bool>("Day092")
                        .HasColumnType("bit");

                    b.Property<bool>("Day093")
                        .HasColumnType("bit");

                    b.Property<bool>("Day094")
                        .HasColumnType("bit");

                    b.Property<bool>("Day095")
                        .HasColumnType("bit");

                    b.Property<bool>("Day096")
                        .HasColumnType("bit");

                    b.Property<bool>("Day097")
                        .HasColumnType("bit");

                    b.Property<bool>("Day098")
                        .HasColumnType("bit");

                    b.Property<bool>("Day099")
                        .HasColumnType("bit");

                    b.Property<bool>("Day100")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("OneHundredDays");
                });
#pragma warning restore 612, 618
        }
    }
}
